package com.jp.wonfes.service.dao.common;

public class DealerDetail extends DealerDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer_detail.product_filed_cd
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    private String productFiledCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer_detail.price
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer_detail.product_filed_cd
     *
     * @return the value of public.dealer_detail.product_filed_cd
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    public String getProductFiledCd() {
        return productFiledCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer_detail.product_filed_cd
     *
     * @param productFiledCd the value for public.dealer_detail.product_filed_cd
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    public void setProductFiledCd(String productFiledCd) {
        this.productFiledCd = productFiledCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer_detail.price
     *
     * @return the value of public.dealer_detail.price
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer_detail.price
     *
     * @param price the value for public.dealer_detail.price
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}