package com.jp.wonfes.service.dao.common;

public class DealerDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer_detail.dealer_id
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer_detail.product_name
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    private String productName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer_detail.dealer_id
     *
     * @return the value of public.dealer_detail.dealer_id
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer_detail.dealer_id
     *
     * @param dealerId the value for public.dealer_detail.dealer_id
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer_detail.product_name
     *
     * @return the value of public.dealer_detail.product_name
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer_detail.product_name
     *
     * @param productName the value for public.dealer_detail.product_name
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }
}