package com.jp.wonfes.service.dao.common;

public class Dealer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.dealer_id
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.name
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.takuban
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    private String takuban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.dealer_icon_cd
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    private String dealerIconCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.hp_link
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    private String hpLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.dealer.tw_link
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    private String twLink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.dealer_id
     *
     * @return the value of public.dealer.dealer_id
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.dealer_id
     *
     * @param dealerId the value for public.dealer.dealer_id
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.name
     *
     * @return the value of public.dealer.name
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.name
     *
     * @param name the value for public.dealer.name
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.takuban
     *
     * @return the value of public.dealer.takuban
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public String getTakuban() {
        return takuban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.takuban
     *
     * @param takuban the value for public.dealer.takuban
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setTakuban(String takuban) {
        this.takuban = takuban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.dealer_icon_cd
     *
     * @return the value of public.dealer.dealer_icon_cd
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public String getDealerIconCd() {
        return dealerIconCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.dealer_icon_cd
     *
     * @param dealerIconCd the value for public.dealer.dealer_icon_cd
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setDealerIconCd(String dealerIconCd) {
        this.dealerIconCd = dealerIconCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.hp_link
     *
     * @return the value of public.dealer.hp_link
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public String getHpLink() {
        return hpLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.hp_link
     *
     * @param hpLink the value for public.dealer.hp_link
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setHpLink(String hpLink) {
        this.hpLink = hpLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.dealer.tw_link
     *
     * @return the value of public.dealer.tw_link
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public String getTwLink() {
        return twLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.dealer.tw_link
     *
     * @param twLink the value for public.dealer.tw_link
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setTwLink(String twLink) {
        this.twLink = twLink;
    }
}