package com.jp.wonfes.service.dao.common;

public class PrdFieldMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.prd_field_master.product_filed_cd
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    private String productFiledCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.prd_field_master.product_filed_name
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    private String productFiledName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.prd_field_master.product_filed_cd
     *
     * @return the value of public.prd_field_master.product_filed_cd
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    public String getProductFiledCd() {
        return productFiledCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.prd_field_master.product_filed_cd
     *
     * @param productFiledCd the value for public.prd_field_master.product_filed_cd
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    public void setProductFiledCd(String productFiledCd) {
        this.productFiledCd = productFiledCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.prd_field_master.product_filed_name
     *
     * @return the value of public.prd_field_master.product_filed_name
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    public String getProductFiledName() {
        return productFiledName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.prd_field_master.product_filed_name
     *
     * @param productFiledName the value for public.prd_field_master.product_filed_name
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    public void setProductFiledName(String productFiledName) {
        this.productFiledName = productFiledName;
    }
}