package com.jp.wonfes.service.dao.common;

import java.util.ArrayList;
import java.util.List;

public class PrdFieldMasterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public PrdFieldMasterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductFiledCdIsNull() {
            addCriterion("product_filed_cd is null");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdIsNotNull() {
            addCriterion("product_filed_cd is not null");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdEqualTo(String value) {
            addCriterion("product_filed_cd =", value, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdNotEqualTo(String value) {
            addCriterion("product_filed_cd <>", value, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdGreaterThan(String value) {
            addCriterion("product_filed_cd >", value, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdGreaterThanOrEqualTo(String value) {
            addCriterion("product_filed_cd >=", value, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdLessThan(String value) {
            addCriterion("product_filed_cd <", value, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdLessThanOrEqualTo(String value) {
            addCriterion("product_filed_cd <=", value, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdLike(String value) {
            addCriterion("product_filed_cd like", value, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdNotLike(String value) {
            addCriterion("product_filed_cd not like", value, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdIn(List<String> values) {
            addCriterion("product_filed_cd in", values, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdNotIn(List<String> values) {
            addCriterion("product_filed_cd not in", values, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdBetween(String value1, String value2) {
            addCriterion("product_filed_cd between", value1, value2, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledCdNotBetween(String value1, String value2) {
            addCriterion("product_filed_cd not between", value1, value2, "productFiledCd");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameIsNull() {
            addCriterion("product_filed_name is null");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameIsNotNull() {
            addCriterion("product_filed_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameEqualTo(String value) {
            addCriterion("product_filed_name =", value, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameNotEqualTo(String value) {
            addCriterion("product_filed_name <>", value, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameGreaterThan(String value) {
            addCriterion("product_filed_name >", value, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_filed_name >=", value, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameLessThan(String value) {
            addCriterion("product_filed_name <", value, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameLessThanOrEqualTo(String value) {
            addCriterion("product_filed_name <=", value, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameLike(String value) {
            addCriterion("product_filed_name like", value, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameNotLike(String value) {
            addCriterion("product_filed_name not like", value, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameIn(List<String> values) {
            addCriterion("product_filed_name in", values, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameNotIn(List<String> values) {
            addCriterion("product_filed_name not in", values, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameBetween(String value1, String value2) {
            addCriterion("product_filed_name between", value1, value2, "productFiledName");
            return (Criteria) this;
        }

        public Criteria andProductFiledNameNotBetween(String value1, String value2) {
            addCriterion("product_filed_name not between", value1, value2, "productFiledName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.prd_field_master
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 07 18:05:35 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}