package com.jp.wonfes.service.dao.common;

public class Usr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usr.uid
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usr.passwd
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usr.unam
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    private String unam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usr.uid
     *
     * @return the value of public.usr.uid
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usr.uid
     *
     * @param uid the value for public.usr.uid
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usr.passwd
     *
     * @return the value of public.usr.passwd
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usr.passwd
     *
     * @param passwd the value for public.usr.passwd
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usr.unam
     *
     * @return the value of public.usr.unam
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public String getUnam() {
        return unam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usr.unam
     *
     * @param unam the value for public.usr.unam
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public void setUnam(String unam) {
        this.unam = unam;
    }
}