package com.jp.wonfes.service.dao.common;

public class UsrRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usr_role.uid
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.usr_role.role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usr_role.uid
     *
     * @return the value of public.usr_role.uid
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usr_role.uid
     *
     * @param uid the value for public.usr_role.uid
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.usr_role.role
     *
     * @return the value of public.usr_role.role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.usr_role.role
     *
     * @param role the value for public.usr_role.role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    public void setRole(String role) {
        this.role = role;
    }
}