package com.jp.wonfes.cmmn.dao.mapper;

import com.jp.wonfes.cmmn.dao.qo.Categories;
import com.jp.wonfes.cmmn.dao.qo.CategoriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int countByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int deleteByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int insert(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int insertSelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    List<Categories> selectByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    Categories selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int updateByExampleSelective(@Param("record") Categories record, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int updateByExample(@Param("record") Categories record, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int updateByPrimaryKeySelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int updateByPrimaryKey(Categories record);
}