package com.jp.wonfes.cmmn.dao.mapper;

import com.jp.wonfes.cmmn.dao.qo.DealersDetailProductsImgsExample;
import com.jp.wonfes.cmmn.dao.qo.DealersDetailProductsImgsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealersDetailProductsImgsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int countByExample(DealersDetailProductsImgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int deleteByExample(DealersDetailProductsImgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int deleteByPrimaryKey(DealersDetailProductsImgsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int insert(DealersDetailProductsImgsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int insertSelective(DealersDetailProductsImgsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    List<DealersDetailProductsImgsKey> selectByExample(DealersDetailProductsImgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int updateByExampleSelective(@Param("record") DealersDetailProductsImgsKey record, @Param("example") DealersDetailProductsImgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int updateByExample(@Param("record") DealersDetailProductsImgsKey record, @Param("example") DealersDetailProductsImgsExample example);
}