package com.jp.wonfes.cmmn.dao.mapper;

import com.jp.wonfes.cmmn.dao.qo.DealersDetailProductsCategoriesExample;
import com.jp.wonfes.cmmn.dao.qo.DealersDetailProductsCategoriesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealersDetailProductsCategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int countByExample(DealersDetailProductsCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int deleteByExample(DealersDetailProductsCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int deleteByPrimaryKey(DealersDetailProductsCategoriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int insert(DealersDetailProductsCategoriesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int insertSelective(DealersDetailProductsCategoriesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    List<DealersDetailProductsCategoriesKey> selectByExample(DealersDetailProductsCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int updateByExampleSelective(@Param("record") DealersDetailProductsCategoriesKey record, @Param("example") DealersDetailProductsCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_categories
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    int updateByExample(@Param("record") DealersDetailProductsCategoriesKey record, @Param("example") DealersDetailProductsCategoriesExample example);
}