package com.jp.wonfes.cmmn.dao.mapper;

import com.jp.wonfes.cmmn.dao.qo.DealersDetailProductsSaledateExample;
import com.jp.wonfes.cmmn.dao.qo.DealersDetailProductsSaledateKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealersDetailProductsSaledateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_saledate
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    int countByExample(DealersDetailProductsSaledateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_saledate
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    int deleteByExample(DealersDetailProductsSaledateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_saledate
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    int deleteByPrimaryKey(DealersDetailProductsSaledateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_saledate
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    int insert(DealersDetailProductsSaledateKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_saledate
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    int insertSelective(DealersDetailProductsSaledateKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_saledate
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    List<DealersDetailProductsSaledateKey> selectByExample(DealersDetailProductsSaledateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_saledate
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    int updateByExampleSelective(@Param("record") DealersDetailProductsSaledateKey record, @Param("example") DealersDetailProductsSaledateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_saledate
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    int updateByExample(@Param("record") DealersDetailProductsSaledateKey record, @Param("example") DealersDetailProductsSaledateExample example);
}