package com.jp.wonfes.cmmn.dao.mapper;

import com.jp.wonfes.cmmn.dao.qo.UsrDetailFavProductsExample;
import com.jp.wonfes.cmmn.dao.qo.UsrDetailFavProductsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsrDetailFavProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_detail_fav_products
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int countByExample(UsrDetailFavProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_detail_fav_products
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int deleteByExample(UsrDetailFavProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_detail_fav_products
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int deleteByPrimaryKey(UsrDetailFavProductsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_detail_fav_products
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int insert(UsrDetailFavProductsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_detail_fav_products
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int insertSelective(UsrDetailFavProductsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_detail_fav_products
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    List<UsrDetailFavProductsKey> selectByExample(UsrDetailFavProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_detail_fav_products
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int updateByExampleSelective(@Param("record") UsrDetailFavProductsKey record, @Param("example") UsrDetailFavProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_detail_fav_products
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int updateByExample(@Param("record") UsrDetailFavProductsKey record, @Param("example") UsrDetailFavProductsExample example);
}