package com.jp.wonfes.cmmn.dao.mapper;

import com.jp.wonfes.cmmn.dao.qo.Usr;
import com.jp.wonfes.cmmn.dao.qo.UsrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int countByExample(UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int deleteByExample(UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int deleteByPrimaryKey(String usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int insert(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int insertSelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    List<Usr> selectByExample(UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    Usr selectByPrimaryKey(String usrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int updateByExampleSelective(@Param("record") Usr record, @Param("example") UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int updateByExample(@Param("record") Usr record, @Param("example") UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int updateByPrimaryKeySelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int updateByPrimaryKey(Usr record);
}