package com.jp.wonfes.cmmn.dao.mapper;

import com.jp.wonfes.cmmn.dao.qo.UsrRoleExample;
import com.jp.wonfes.cmmn.dao.qo.UsrRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsrRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int countByExample(UsrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int deleteByExample(UsrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int deleteByPrimaryKey(UsrRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int insert(UsrRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int insertSelective(UsrRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    List<UsrRoleKey> selectByExample(UsrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int updateByExampleSelective(@Param("record") UsrRoleKey record, @Param("example") UsrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.usr_role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    int updateByExample(@Param("record") UsrRoleKey record, @Param("example") UsrRoleExample example);
}