package com.jp.wonfes.cmmn.dao.qo;

public class Categories {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.categories.category_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.categories.category_name
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.categories.category_name_reading
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private String categoryNameReading;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.categories.category_id
     *
     * @return the value of wfs.categories.category_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.categories.category_id
     *
     * @param categoryId the value for wfs.categories.category_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.categories.category_name
     *
     * @return the value of wfs.categories.category_name
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.categories.category_name
     *
     * @param categoryName the value for wfs.categories.category_name
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.categories.category_name_reading
     *
     * @return the value of wfs.categories.category_name_reading
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public String getCategoryNameReading() {
        return categoryNameReading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.categories.category_name_reading
     *
     * @param categoryNameReading the value for wfs.categories.category_name_reading
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setCategoryNameReading(String categoryNameReading) {
        this.categoryNameReading = categoryNameReading;
    }
}