package com.jp.wonfes.cmmn.dao.qo;

public class DealersDetailProductsImgsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_imgs.dealer_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_imgs.product_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_imgs.img_product_file
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private String imgProductFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_imgs.dealer_id
     *
     * @return the value of wfs.dealers_detail_products_imgs.dealer_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_imgs.dealer_id
     *
     * @param dealerId the value for wfs.dealers_detail_products_imgs.dealer_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_imgs.product_id
     *
     * @return the value of wfs.dealers_detail_products_imgs.product_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_imgs.product_id
     *
     * @param productId the value for wfs.dealers_detail_products_imgs.product_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_imgs.img_product_file
     *
     * @return the value of wfs.dealers_detail_products_imgs.img_product_file
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public String getImgProductFile() {
        return imgProductFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_imgs.img_product_file
     *
     * @param imgProductFile the value for wfs.dealers_detail_products_imgs.img_product_file
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setImgProductFile(String imgProductFile) {
        this.imgProductFile = imgProductFile;
    }
}