package com.jp.wonfes.cmmn.dao.qo;

public class DealersDetailProducts extends DealersDetailProductsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products.product_name
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products.price
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products.introduce
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products.season_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer seasonId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products.product_name
     *
     * @return the value of wfs.dealers_detail_products.product_name
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products.product_name
     *
     * @param productName the value for wfs.dealers_detail_products.product_name
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products.price
     *
     * @return the value of wfs.dealers_detail_products.price
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products.price
     *
     * @param price the value for wfs.dealers_detail_products.price
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products.introduce
     *
     * @return the value of wfs.dealers_detail_products.introduce
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products.introduce
     *
     * @param introduce the value for wfs.dealers_detail_products.introduce
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products.season_id
     *
     * @return the value of wfs.dealers_detail_products.season_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getSeasonId() {
        return seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products.season_id
     *
     * @param seasonId the value for wfs.dealers_detail_products.season_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }
}