package com.jp.wonfes.cmmn.dao.qo;

public class DealersDetailProductsImgsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_imgs.dealer_id
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_imgs.product_id
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_imgs.img_seq
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    private Integer imgSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_imgs.dealer_id
     *
     * @return the value of wfs.dealers_detail_products_imgs.dealer_id
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_imgs.dealer_id
     *
     * @param dealerId the value for wfs.dealers_detail_products_imgs.dealer_id
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_imgs.product_id
     *
     * @return the value of wfs.dealers_detail_products_imgs.product_id
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_imgs.product_id
     *
     * @param productId the value for wfs.dealers_detail_products_imgs.product_id
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_imgs.img_seq
     *
     * @return the value of wfs.dealers_detail_products_imgs.img_seq
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    public Integer getImgSeq() {
        return imgSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_imgs.img_seq
     *
     * @param imgSeq the value for wfs.dealers_detail_products_imgs.img_seq
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    public void setImgSeq(Integer imgSeq) {
        this.imgSeq = imgSeq;
    }
}