package com.jp.wonfes.cmmn.dao.qo;

public class Dealers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers.dealer_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers.dealer_name
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private String dealerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers.bussines_type
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private String bussinesType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers.takuban
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private String takuban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers.hp_link
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private String hpLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers.tw_link
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private String twLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers.sort_key
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private String sortKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers.img_icon_file
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private String imgIconFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers.dealer_id
     *
     * @return the value of wfs.dealers.dealer_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers.dealer_id
     *
     * @param dealerId the value for wfs.dealers.dealer_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers.dealer_name
     *
     * @return the value of wfs.dealers.dealer_name
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getDealerName() {
        return dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers.dealer_name
     *
     * @param dealerName the value for wfs.dealers.dealer_name
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setDealerName(String dealerName) {
        this.dealerName = dealerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers.bussines_type
     *
     * @return the value of wfs.dealers.bussines_type
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getBussinesType() {
        return bussinesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers.bussines_type
     *
     * @param bussinesType the value for wfs.dealers.bussines_type
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setBussinesType(String bussinesType) {
        this.bussinesType = bussinesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers.takuban
     *
     * @return the value of wfs.dealers.takuban
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getTakuban() {
        return takuban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers.takuban
     *
     * @param takuban the value for wfs.dealers.takuban
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setTakuban(String takuban) {
        this.takuban = takuban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers.hp_link
     *
     * @return the value of wfs.dealers.hp_link
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getHpLink() {
        return hpLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers.hp_link
     *
     * @param hpLink the value for wfs.dealers.hp_link
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setHpLink(String hpLink) {
        this.hpLink = hpLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers.tw_link
     *
     * @return the value of wfs.dealers.tw_link
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getTwLink() {
        return twLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers.tw_link
     *
     * @param twLink the value for wfs.dealers.tw_link
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setTwLink(String twLink) {
        this.twLink = twLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers.sort_key
     *
     * @return the value of wfs.dealers.sort_key
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getSortKey() {
        return sortKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers.sort_key
     *
     * @param sortKey the value for wfs.dealers.sort_key
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setSortKey(String sortKey) {
        this.sortKey = sortKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers.img_icon_file
     *
     * @return the value of wfs.dealers.img_icon_file
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getImgIconFile() {
        return imgIconFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers.img_icon_file
     *
     * @param imgIconFile the value for wfs.dealers.img_icon_file
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setImgIconFile(String imgIconFile) {
        this.imgIconFile = imgIconFile;
    }
}