package com.jp.wonfes.cmmn.dao.qo;

public class DealersDetailProductsImgs extends DealersDetailProductsImgsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_imgs.img_product_file
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    private String imgProductFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_imgs.img_product_file
     *
     * @return the value of wfs.dealers_detail_products_imgs.img_product_file
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    public String getImgProductFile() {
        return imgProductFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_imgs.img_product_file
     *
     * @param imgProductFile the value for wfs.dealers_detail_products_imgs.img_product_file
     *
     * @mbggenerated Sat Jan 05 12:39:34 JST 2019
     */
    public void setImgProductFile(String imgProductFile) {
        this.imgProductFile = imgProductFile;
    }
}