package com.jp.wonfes.cmmn.dao.qo;

public class DealersDetailProductsCategoriesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_categories.dealer_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_categories.product_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_categories.category_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_categories.dealer_id
     *
     * @return the value of wfs.dealers_detail_products_categories.dealer_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_categories.dealer_id
     *
     * @param dealerId the value for wfs.dealers_detail_products_categories.dealer_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_categories.product_id
     *
     * @return the value of wfs.dealers_detail_products_categories.product_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_categories.product_id
     *
     * @param productId the value for wfs.dealers_detail_products_categories.product_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_categories.category_id
     *
     * @return the value of wfs.dealers_detail_products_categories.category_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_categories.category_id
     *
     * @param categoryId the value for wfs.dealers_detail_products_categories.category_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}