package com.jp.wonfes.cmmn.dao.qo;

import java.util.ArrayList;
import java.util.List;

public class DealersDetailProductsImgsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public DealersDetailProductsImgsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDealerIdIsNull() {
            addCriterion("dealer_id is null");
            return (Criteria) this;
        }

        public Criteria andDealerIdIsNotNull() {
            addCriterion("dealer_id is not null");
            return (Criteria) this;
        }

        public Criteria andDealerIdEqualTo(Integer value) {
            addCriterion("dealer_id =", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotEqualTo(Integer value) {
            addCriterion("dealer_id <>", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdGreaterThan(Integer value) {
            addCriterion("dealer_id >", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dealer_id >=", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLessThan(Integer value) {
            addCriterion("dealer_id <", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLessThanOrEqualTo(Integer value) {
            addCriterion("dealer_id <=", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdIn(List<Integer> values) {
            addCriterion("dealer_id in", values, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotIn(List<Integer> values) {
            addCriterion("dealer_id not in", values, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdBetween(Integer value1, Integer value2) {
            addCriterion("dealer_id between", value1, value2, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dealer_id not between", value1, value2, "dealerId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andImgProductFileIsNull() {
            addCriterion("img_product_file is null");
            return (Criteria) this;
        }

        public Criteria andImgProductFileIsNotNull() {
            addCriterion("img_product_file is not null");
            return (Criteria) this;
        }

        public Criteria andImgProductFileEqualTo(String value) {
            addCriterion("img_product_file =", value, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileNotEqualTo(String value) {
            addCriterion("img_product_file <>", value, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileGreaterThan(String value) {
            addCriterion("img_product_file >", value, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileGreaterThanOrEqualTo(String value) {
            addCriterion("img_product_file >=", value, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileLessThan(String value) {
            addCriterion("img_product_file <", value, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileLessThanOrEqualTo(String value) {
            addCriterion("img_product_file <=", value, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileLike(String value) {
            addCriterion("img_product_file like", value, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileNotLike(String value) {
            addCriterion("img_product_file not like", value, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileIn(List<String> values) {
            addCriterion("img_product_file in", values, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileNotIn(List<String> values) {
            addCriterion("img_product_file not in", values, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileBetween(String value1, String value2) {
            addCriterion("img_product_file between", value1, value2, "imgProductFile");
            return (Criteria) this;
        }

        public Criteria andImgProductFileNotBetween(String value1, String value2) {
            addCriterion("img_product_file not between", value1, value2, "imgProductFile");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 29 23:41:32 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wfs.dealers_detail_products_imgs
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}