package com.jp.wonfes.cmmn.dao.qo;

import java.util.ArrayList;
import java.util.List;

public class DealersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public DealersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDealerIdIsNull() {
            addCriterion("dealer_id is null");
            return (Criteria) this;
        }

        public Criteria andDealerIdIsNotNull() {
            addCriterion("dealer_id is not null");
            return (Criteria) this;
        }

        public Criteria andDealerIdEqualTo(Integer value) {
            addCriterion("dealer_id =", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotEqualTo(Integer value) {
            addCriterion("dealer_id <>", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdGreaterThan(Integer value) {
            addCriterion("dealer_id >", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dealer_id >=", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLessThan(Integer value) {
            addCriterion("dealer_id <", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdLessThanOrEqualTo(Integer value) {
            addCriterion("dealer_id <=", value, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdIn(List<Integer> values) {
            addCriterion("dealer_id in", values, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotIn(List<Integer> values) {
            addCriterion("dealer_id not in", values, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdBetween(Integer value1, Integer value2) {
            addCriterion("dealer_id between", value1, value2, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dealer_id not between", value1, value2, "dealerId");
            return (Criteria) this;
        }

        public Criteria andDealerNameIsNull() {
            addCriterion("dealer_name is null");
            return (Criteria) this;
        }

        public Criteria andDealerNameIsNotNull() {
            addCriterion("dealer_name is not null");
            return (Criteria) this;
        }

        public Criteria andDealerNameEqualTo(String value) {
            addCriterion("dealer_name =", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotEqualTo(String value) {
            addCriterion("dealer_name <>", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameGreaterThan(String value) {
            addCriterion("dealer_name >", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameGreaterThanOrEqualTo(String value) {
            addCriterion("dealer_name >=", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameLessThan(String value) {
            addCriterion("dealer_name <", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameLessThanOrEqualTo(String value) {
            addCriterion("dealer_name <=", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameLike(String value) {
            addCriterion("dealer_name like", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotLike(String value) {
            addCriterion("dealer_name not like", value, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameIn(List<String> values) {
            addCriterion("dealer_name in", values, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotIn(List<String> values) {
            addCriterion("dealer_name not in", values, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameBetween(String value1, String value2) {
            addCriterion("dealer_name between", value1, value2, "dealerName");
            return (Criteria) this;
        }

        public Criteria andDealerNameNotBetween(String value1, String value2) {
            addCriterion("dealer_name not between", value1, value2, "dealerName");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeIsNull() {
            addCriterion("bussines_type is null");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeIsNotNull() {
            addCriterion("bussines_type is not null");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeEqualTo(String value) {
            addCriterion("bussines_type =", value, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeNotEqualTo(String value) {
            addCriterion("bussines_type <>", value, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeGreaterThan(String value) {
            addCriterion("bussines_type >", value, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeGreaterThanOrEqualTo(String value) {
            addCriterion("bussines_type >=", value, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeLessThan(String value) {
            addCriterion("bussines_type <", value, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeLessThanOrEqualTo(String value) {
            addCriterion("bussines_type <=", value, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeLike(String value) {
            addCriterion("bussines_type like", value, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeNotLike(String value) {
            addCriterion("bussines_type not like", value, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeIn(List<String> values) {
            addCriterion("bussines_type in", values, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeNotIn(List<String> values) {
            addCriterion("bussines_type not in", values, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeBetween(String value1, String value2) {
            addCriterion("bussines_type between", value1, value2, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andBussinesTypeNotBetween(String value1, String value2) {
            addCriterion("bussines_type not between", value1, value2, "bussinesType");
            return (Criteria) this;
        }

        public Criteria andTakubanIsNull() {
            addCriterion("takuban is null");
            return (Criteria) this;
        }

        public Criteria andTakubanIsNotNull() {
            addCriterion("takuban is not null");
            return (Criteria) this;
        }

        public Criteria andTakubanEqualTo(String value) {
            addCriterion("takuban =", value, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanNotEqualTo(String value) {
            addCriterion("takuban <>", value, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanGreaterThan(String value) {
            addCriterion("takuban >", value, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanGreaterThanOrEqualTo(String value) {
            addCriterion("takuban >=", value, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanLessThan(String value) {
            addCriterion("takuban <", value, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanLessThanOrEqualTo(String value) {
            addCriterion("takuban <=", value, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanLike(String value) {
            addCriterion("takuban like", value, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanNotLike(String value) {
            addCriterion("takuban not like", value, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanIn(List<String> values) {
            addCriterion("takuban in", values, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanNotIn(List<String> values) {
            addCriterion("takuban not in", values, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanBetween(String value1, String value2) {
            addCriterion("takuban between", value1, value2, "takuban");
            return (Criteria) this;
        }

        public Criteria andTakubanNotBetween(String value1, String value2) {
            addCriterion("takuban not between", value1, value2, "takuban");
            return (Criteria) this;
        }

        public Criteria andHpLinkIsNull() {
            addCriterion("hp_link is null");
            return (Criteria) this;
        }

        public Criteria andHpLinkIsNotNull() {
            addCriterion("hp_link is not null");
            return (Criteria) this;
        }

        public Criteria andHpLinkEqualTo(String value) {
            addCriterion("hp_link =", value, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkNotEqualTo(String value) {
            addCriterion("hp_link <>", value, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkGreaterThan(String value) {
            addCriterion("hp_link >", value, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkGreaterThanOrEqualTo(String value) {
            addCriterion("hp_link >=", value, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkLessThan(String value) {
            addCriterion("hp_link <", value, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkLessThanOrEqualTo(String value) {
            addCriterion("hp_link <=", value, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkLike(String value) {
            addCriterion("hp_link like", value, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkNotLike(String value) {
            addCriterion("hp_link not like", value, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkIn(List<String> values) {
            addCriterion("hp_link in", values, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkNotIn(List<String> values) {
            addCriterion("hp_link not in", values, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkBetween(String value1, String value2) {
            addCriterion("hp_link between", value1, value2, "hpLink");
            return (Criteria) this;
        }

        public Criteria andHpLinkNotBetween(String value1, String value2) {
            addCriterion("hp_link not between", value1, value2, "hpLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkIsNull() {
            addCriterion("tw_link is null");
            return (Criteria) this;
        }

        public Criteria andTwLinkIsNotNull() {
            addCriterion("tw_link is not null");
            return (Criteria) this;
        }

        public Criteria andTwLinkEqualTo(String value) {
            addCriterion("tw_link =", value, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkNotEqualTo(String value) {
            addCriterion("tw_link <>", value, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkGreaterThan(String value) {
            addCriterion("tw_link >", value, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkGreaterThanOrEqualTo(String value) {
            addCriterion("tw_link >=", value, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkLessThan(String value) {
            addCriterion("tw_link <", value, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkLessThanOrEqualTo(String value) {
            addCriterion("tw_link <=", value, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkLike(String value) {
            addCriterion("tw_link like", value, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkNotLike(String value) {
            addCriterion("tw_link not like", value, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkIn(List<String> values) {
            addCriterion("tw_link in", values, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkNotIn(List<String> values) {
            addCriterion("tw_link not in", values, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkBetween(String value1, String value2) {
            addCriterion("tw_link between", value1, value2, "twLink");
            return (Criteria) this;
        }

        public Criteria andTwLinkNotBetween(String value1, String value2) {
            addCriterion("tw_link not between", value1, value2, "twLink");
            return (Criteria) this;
        }

        public Criteria andSortKeyIsNull() {
            addCriterion("sort_key is null");
            return (Criteria) this;
        }

        public Criteria andSortKeyIsNotNull() {
            addCriterion("sort_key is not null");
            return (Criteria) this;
        }

        public Criteria andSortKeyEqualTo(String value) {
            addCriterion("sort_key =", value, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyNotEqualTo(String value) {
            addCriterion("sort_key <>", value, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyGreaterThan(String value) {
            addCriterion("sort_key >", value, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyGreaterThanOrEqualTo(String value) {
            addCriterion("sort_key >=", value, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyLessThan(String value) {
            addCriterion("sort_key <", value, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyLessThanOrEqualTo(String value) {
            addCriterion("sort_key <=", value, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyLike(String value) {
            addCriterion("sort_key like", value, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyNotLike(String value) {
            addCriterion("sort_key not like", value, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyIn(List<String> values) {
            addCriterion("sort_key in", values, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyNotIn(List<String> values) {
            addCriterion("sort_key not in", values, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyBetween(String value1, String value2) {
            addCriterion("sort_key between", value1, value2, "sortKey");
            return (Criteria) this;
        }

        public Criteria andSortKeyNotBetween(String value1, String value2) {
            addCriterion("sort_key not between", value1, value2, "sortKey");
            return (Criteria) this;
        }

        public Criteria andImgIconFileIsNull() {
            addCriterion("img_icon_file is null");
            return (Criteria) this;
        }

        public Criteria andImgIconFileIsNotNull() {
            addCriterion("img_icon_file is not null");
            return (Criteria) this;
        }

        public Criteria andImgIconFileEqualTo(String value) {
            addCriterion("img_icon_file =", value, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileNotEqualTo(String value) {
            addCriterion("img_icon_file <>", value, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileGreaterThan(String value) {
            addCriterion("img_icon_file >", value, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileGreaterThanOrEqualTo(String value) {
            addCriterion("img_icon_file >=", value, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileLessThan(String value) {
            addCriterion("img_icon_file <", value, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileLessThanOrEqualTo(String value) {
            addCriterion("img_icon_file <=", value, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileLike(String value) {
            addCriterion("img_icon_file like", value, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileNotLike(String value) {
            addCriterion("img_icon_file not like", value, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileIn(List<String> values) {
            addCriterion("img_icon_file in", values, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileNotIn(List<String> values) {
            addCriterion("img_icon_file not in", values, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileBetween(String value1, String value2) {
            addCriterion("img_icon_file between", value1, value2, "imgIconFile");
            return (Criteria) this;
        }

        public Criteria andImgIconFileNotBetween(String value1, String value2) {
            addCriterion("img_icon_file not between", value1, value2, "imgIconFile");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wfs.dealers
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 20 11:37:01 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wfs.dealers
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}