package com.jp.wonfes.cmmn.dao.qo;

public class DealersDetailProductsSaledateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_saledate.dealer_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_saledate.product_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.dealers_detail_products_saledate.event_date_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private Integer eventDateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_saledate.dealer_id
     *
     * @return the value of wfs.dealers_detail_products_saledate.dealer_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_saledate.dealer_id
     *
     * @param dealerId the value for wfs.dealers_detail_products_saledate.dealer_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_saledate.product_id
     *
     * @return the value of wfs.dealers_detail_products_saledate.product_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_saledate.product_id
     *
     * @param productId the value for wfs.dealers_detail_products_saledate.product_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.dealers_detail_products_saledate.event_date_id
     *
     * @return the value of wfs.dealers_detail_products_saledate.event_date_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public Integer getEventDateId() {
        return eventDateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.dealers_detail_products_saledate.event_date_id
     *
     * @param eventDateId the value for wfs.dealers_detail_products_saledate.event_date_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setEventDateId(Integer eventDateId) {
        this.eventDateId = eventDateId;
    }
}