package com.jp.wonfes.cmmn.dao.qo;

import java.util.Date;

public class EventDates {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.event_dates.event_date_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private Integer eventDateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.event_dates.event_aboutdate
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private String eventAboutdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.event_dates.event_date
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private Date eventDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.event_dates.event_season
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    private String eventSeason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.event_dates.event_date_id
     *
     * @return the value of wfs.event_dates.event_date_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public Integer getEventDateId() {
        return eventDateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.event_dates.event_date_id
     *
     * @param eventDateId the value for wfs.event_dates.event_date_id
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setEventDateId(Integer eventDateId) {
        this.eventDateId = eventDateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.event_dates.event_aboutdate
     *
     * @return the value of wfs.event_dates.event_aboutdate
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getEventAboutdate() {
        return eventAboutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.event_dates.event_aboutdate
     *
     * @param eventAboutdate the value for wfs.event_dates.event_aboutdate
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setEventAboutdate(String eventAboutdate) {
        this.eventAboutdate = eventAboutdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.event_dates.event_date
     *
     * @return the value of wfs.event_dates.event_date
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public Date getEventDate() {
        return eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.event_dates.event_date
     *
     * @param eventDate the value for wfs.event_dates.event_date
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.event_dates.event_season
     *
     * @return the value of wfs.event_dates.event_season
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public String getEventSeason() {
        return eventSeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.event_dates.event_season
     *
     * @param eventSeason the value for wfs.event_dates.event_season
     *
     * @mbggenerated Sat Dec 29 23:41:32 JST 2018
     */
    public void setEventSeason(String eventSeason) {
        this.eventSeason = eventSeason;
    }
}