package com.jp.wonfes.cmmn.dao.qo;

import java.util.Date;

public class Usr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr.usr_id
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    private String usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr.passwd
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr.user_name
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr.ins_date
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    private Date insDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr.upd_date
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    private Date updDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr.usr_id
     *
     * @return the value of wfs.usr.usr_id
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr.usr_id
     *
     * @param usrId the value for wfs.usr.usr_id
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr.passwd
     *
     * @return the value of wfs.usr.passwd
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr.passwd
     *
     * @param passwd the value for wfs.usr.passwd
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr.user_name
     *
     * @return the value of wfs.usr.user_name
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr.user_name
     *
     * @param userName the value for wfs.usr.user_name
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr.ins_date
     *
     * @return the value of wfs.usr.ins_date
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public Date getInsDate() {
        return insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr.ins_date
     *
     * @param insDate the value for wfs.usr.ins_date
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public void setInsDate(Date insDate) {
        this.insDate = insDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr.upd_date
     *
     * @return the value of wfs.usr.upd_date
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public Date getUpdDate() {
        return updDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr.upd_date
     *
     * @param updDate the value for wfs.usr.upd_date
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public void setUpdDate(Date updDate) {
        this.updDate = updDate;
    }
}