package com.jp.wonfes.cmmn.dao.qo;

public class UsrDetailFavProductsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr_detail_fav_products.usr_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private String usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr_detail_fav_products.dealer_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer dealerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr_detail_fav_products.product_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr_detail_fav_products.usr_id
     *
     * @return the value of wfs.usr_detail_fav_products.usr_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr_detail_fav_products.usr_id
     *
     * @param usrId the value for wfs.usr_detail_fav_products.usr_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr_detail_fav_products.dealer_id
     *
     * @return the value of wfs.usr_detail_fav_products.dealer_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getDealerId() {
        return dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr_detail_fav_products.dealer_id
     *
     * @param dealerId the value for wfs.usr_detail_fav_products.dealer_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setDealerId(Integer dealerId) {
        this.dealerId = dealerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr_detail_fav_products.product_id
     *
     * @return the value of wfs.usr_detail_fav_products.product_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr_detail_fav_products.product_id
     *
     * @param productId the value for wfs.usr_detail_fav_products.product_id
     *
     * @mbggenerated Sat Oct 20 11:37:01 JST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}