package com.jp.wonfes.cmmn.dao.qo;

public class UsrRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr_role.usr_id
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    private String usrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wfs.usr_role.role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr_role.usr_id
     *
     * @return the value of wfs.usr_role.usr_id
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr_role.usr_id
     *
     * @param usrId the value for wfs.usr_role.usr_id
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wfs.usr_role.role
     *
     * @return the value of wfs.usr_role.role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wfs.usr_role.role
     *
     * @param role the value for wfs.usr_role.role
     *
     * @mbggenerated Sat Dec 29 23:41:33 JST 2018
     */
    public void setRole(String role) {
        this.role = role;
    }
}