package com.jp.wonfes.service.dao.common.mapper;

import com.jp.wonfes.service.dao.common.DealerDetail;
import com.jp.wonfes.service.dao.common.DealerDetailExample;
import com.jp.wonfes.service.dao.common.DealerDetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealerDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    int countByExample(DealerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    int deleteByExample(DealerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    int deleteByPrimaryKey(DealerDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    int insert(DealerDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    int insertSelective(DealerDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    List<DealerDetail> selectByExample(DealerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    DealerDetail selectByPrimaryKey(DealerDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    int updateByExampleSelective(@Param("record") DealerDetail record, @Param("example") DealerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    int updateByExample(@Param("record") DealerDetail record, @Param("example") DealerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    int updateByPrimaryKeySelective(DealerDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer_detail
     *
     * @mbggenerated Thu Apr 05 22:23:04 JST 2018
     */
    int updateByPrimaryKey(DealerDetail record);
}