package com.jp.wonfes.service.dao.common.mapper;

import com.jp.wonfes.service.dao.common.Dealer;
import com.jp.wonfes.service.dao.common.DealerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DealerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int countByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int deleteByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int deleteByPrimaryKey(Integer dealerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int insert(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int insertSelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    List<Dealer> selectByExample(DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    Dealer selectByPrimaryKey(Integer dealerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int updateByExampleSelective(@Param("record") Dealer record, @Param("example") DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int updateByExample(@Param("record") Dealer record, @Param("example") DealerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int updateByPrimaryKeySelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.dealer
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int updateByPrimaryKey(Dealer record);
}