package com.jp.wonfes.service.dao.common.mapper;

import com.jp.wonfes.service.dao.common.PrdFieldMaster;
import com.jp.wonfes.service.dao.common.PrdFieldMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrdFieldMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int countByExample(PrdFieldMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int deleteByExample(PrdFieldMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int deleteByPrimaryKey(String productFiledCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int insert(PrdFieldMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int insertSelective(PrdFieldMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    List<PrdFieldMaster> selectByExample(PrdFieldMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    PrdFieldMaster selectByPrimaryKey(String productFiledCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int updateByExampleSelective(@Param("record") PrdFieldMaster record, @Param("example") PrdFieldMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int updateByExample(@Param("record") PrdFieldMaster record, @Param("example") PrdFieldMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int updateByPrimaryKeySelective(PrdFieldMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.prd_field_master
     *
     * @mbggenerated Sat Apr 07 18:05:35 JST 2018
     */
    int updateByPrimaryKey(PrdFieldMaster record);
}