package com.jp.wonfes.service.dao.common.mapper;

import com.jp.wonfes.service.dao.common.UsrRoleExample;
import com.jp.wonfes.service.dao.common.UsrRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsrRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usr_role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    int countByExample(UsrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usr_role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    int deleteByExample(UsrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usr_role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    int deleteByPrimaryKey(UsrRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usr_role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    int insert(UsrRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usr_role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    int insertSelective(UsrRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usr_role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    List<UsrRoleKey> selectByExample(UsrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usr_role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    int updateByExampleSelective(@Param("record") UsrRoleKey record, @Param("example") UsrRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.usr_role
     *
     * @mbggenerated Mon Apr 30 15:40:57 JST 2018
     */
    int updateByExample(@Param("record") UsrRoleKey record, @Param("example") UsrRoleExample example);
}